Meetings System
he4rt/he4rt-bot-api pull request #9
Opened 2022-12-07 14:08 UTC by PedroPMS

2022-12-07 23:06 UTC, DanielHe4rt commented on app/Actions/Event/Meeting/AttendMeeting.php
> +    public function __construct(MeetingParticipantsRepository $repository, UsersRepository $usersRepository, MeetingRepository $meetingRepository)
identação plz

2022-12-07 23:07 UTC, DanielHe4rt commented on app/Actions/Event/Meeting/AttendMeeting.php
> +    public function __construct(MeetingParticipantsRepository $repository, UsersRepository $usersRepository, MeetingRepository $meetingRepository)
```suggestion
    public function __construct(
    MeetingParticipantsRepository $repository, 
    UsersRepository $usersRepository, 
    MeetingRepository $meetingRepository
    )
```

2022-12-07 23:34 UTC, DanielHe4rt requested changes

2022-12-07 23:34 UTC, DanielHe4rt commented on app/Actions/Event/Meeting/AttendMeeting.php
> +        $meeting = $this->meetingRepository->find($payload['meeting_id']);
Pelo o meu entendimento da feature, assim que uma reunião ser iniciada a pessoa vai poder se juntar apenas a reunião ativa.

O bot enviaria apenas o DiscordID em um primeiro momento até entendermos como implementar o log de tempo.

2022-12-07 23:34 UTC, danielhe4rt commented on app/Http/Controllers/Events/MeettingsController.php
> +class MeettingsController extends Controller
```suggestion
class MeetingsController extends Controller
```

2022-12-07 23:34 UTC, danielhe4rt commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function index(IndexMeeting $action): JsonResponse
```suggestion
    public function getMeetings(IndexMeeting $action): JsonResponse
```

2022-12-07 23:34 UTC, danielhe4rt commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function store(Request $request, CreateMeeting $action): JsonResponse
```suggestion
    public function postMeeting(Request $request, CreateMeeting $action): JsonResponse
```

2022-12-07 23:34 UTC, DanielHe4rt commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function endMeeting(Request $request, int $meetingId, UpdateMeeting $action): JsonResponse
```suggestion
    public function postEndMeeting(Request $request, int $meetingId, UpdateMeeting $action): JsonResponse
```

2022-12-07 23:34 UTC, danielhe4rt commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function attendMeeting(Request $request, AttendMeeting $action): JsonResponse
```suggestion
    public function postAttendMeeting(Request $request, AttendMeeting $action): JsonResponse
```

2022-12-07 23:34 UTC, DanielHe4rt commented on tests/Feature/Events/Meetings/IndexMeetingTest.php
> +                    '*' => [
* = bobo

2022-12-07 23:50 UTC, PedroPMS commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function index(IndexMeeting $action): JsonResponse
Ajustado.

2022-12-07 23:50 UTC, PedroPMS commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function endMeeting(Request $request, int $meetingId, UpdateMeeting $action): JsonResponse
Ajustado.

2022-12-07 23:55 UTC, PedroPMS commented on tests/Feature/Events/Meetings/IndexMeetingTest.php
> +                    '*' => [
Ajustado.

2022-12-07 23:56 UTC, PedroPMS commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function store(Request $request, CreateMeeting $action): JsonResponse
Ajustado.

2022-12-07 23:56 UTC, PedroPMS commented on app/Http/Controllers/Events/MeettingsController.php
> +    public function attendMeeting(Request $request, AttendMeeting $action): JsonResponse
Ajustado.

2022-12-08 00:07 UTC, PedroPMS commented on app/Actions/Event/Meeting/AttendMeeting.php
> +        $meeting = $this->meetingRepository->find($payload['meeting_id']);
Ajustado para atualizar as reuniões ativas.

2022-12-08 00:09 UTC, PedroPMS commented
A parte de adicionar a ata da reunião não foi implementada pois n sei se vai ser feito via bot ou n. Se for via bot terá q ser feito no mesmo esquema do `putEndMeeting`

2022-12-08 01:58 UTC, DanielHe4rt commented
Talvez se a gente listasse as reuniões com data via discord e selecionasse o id da reunião pro put, seria mais interessante. 

Mas ai seria uma rota PATCH apenas para o resumo da reunião. O que você acha? @Novout

2022-12-08 02:00 UTC, Novout commented
Por conta da reunião ser de id único (chat do discord), o ideal seria ter um comando de ADM/MOD para registrar a reunião, de id única, para dai a partir desse id criar outros comandos para a devida manipulação.

2022-12-08 18:26 UTC, DanielHe4rt commented on app/Actions/Event/Meeting/AttendMeeting.php
> +        $meeting = $this->meetingRepository->getFirstActiveMeeting();
```suggestion
        $meeting = $this->meetingRepository->getActiveMeeting();
```

2022-12-08 19:38 UTC, DanielHe4rt commented on app/Actions/Event/Meeting/AttendMeeting.php
> +            throw MeetingsException::noAtiveMeetings();
```suggestion
            throw MeetingsException::noActiveMeetings();
```

2022-12-10 02:47 UTC, Novout reviewed
qual a diferença entre `meeting_id` e `meeting_type_id`?

2022-12-10 17:56 UTC, DanielHe4rt commented
> 

O meeting_type_id referencia o tipo de reunião e hoje temos apenas 2.

1 - reunião semanal
2 - reunião das primas.

2022-12-10 18:07 UTC, DanielHe4rt commented on app/Models/Events/Meeting.php
> +        'user_created_id',
Acho que poderia ficar mais sucinto e explicativo com algo do tipo `author_id` ou `admin_id`. 
```suggestion
        'admin_id',
```

2022-12-10 20:07 UTC, DanielHe4rt approved these changes

2022-12-10 20:07 UTC, merged